name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build_MFconv:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          sudo apt-get update
      - run: >
          cmake
          -D CMAKE_CXX_COMPILER=g++
          -S . -B build/
      - run: make -j4 VERBOSE=1
        working-directory: build/
